import { UberLevel } from '../enum/uberlevel'
import { UserRatingI } from './types'

export const UserRatingList: UserRatingI[] = [
  {
    id: 'id1',
    nickname: 'ALL-WINNER',
    secondName: 'Petrov',
    firstName: 'Vasya',
    pts: 2234,
    rang: UberLevel.UBERPREDATOR,
  },
  {
    id: 'id2',
    nickname: 'ALL-LOSER',
    secondName: 'Lol',
    firstName: 'Roma',
    pts: 10,
    rang: UberLevel.UBERVEGETABLE,
  },
  {
    id: 'id3',
    nickname: 'MIDDLE',
    secondName: 'Shnurov',
    firstName: 'Misha',
    pts: 1000,
    rang: UberLevel.GRASSFEEDING,
  },
  {
    id: 'id4',
    nickname: 'JUNIOR',
    secondName: 'Drysh',
    firstName: 'Lesha',
    pts: 999,
    rang: UberLevel.VEGETABLE,
  },
  {
    id: 'id5',
    nickname: 'SENIOR',
    secondName: 'Sobol',
    firstName: 'Ilya',
    pts: 1300,
    rang: UberLevel.FLASHEATING,
  },
  {
    id: 'id6',
    nickname: 'ALL-WINNER-1',
    secondName: 'Petrov',
    firstName: 'Vasya',
    pts: 2234,
    rang: UberLevel.UBERPREDATOR,
  },
  {
    id: 'id7',
    nickname: 'ALL-LOSER-1',
    secondName: 'Lol',
    firstName: 'Roma',
    pts: 10,
    rang: UberLevel.UBERVEGETABLE,
  },
  {
    id: 'id8',
    nickname: 'MIDDLE-1',
    secondName: 'Shnurov',
    firstName: 'Misha',
    pts: 1000,
    rang: UberLevel.GRASSFEEDING,
  },
  {
    id: 'id9',
    nickname: 'JUNIOR-1',
    secondName: 'Drysh',
    firstName: 'Lesha',
    pts: 999,
    rang: UberLevel.VEGETABLE,
  },
  {
    id: 'id10',
    nickname: 'SENIOR-1',
    secondName: 'Sobol',
    firstName: 'Ilya',
    pts: 1300,
    rang: UberLevel.FLASHEATING,
  },
]
