import { UberLevel } from '../enum/uberlevel'
import { UserRatingI } from './types'

export let UserRatingList: UserRatingI[] = [
  {
    id: 'id1',
    username: 'ALL-WINNER',
    lastName: 'Petrov',
    firstName: 'Vasya',
    rating: 2234,
    rang: UberLevel.UBERPREDATOR,
  },
  {
    id: 'id2',
    username: 'ALL-LOSER',
    lastName: 'Lol',
    firstName: 'Roma',
    rating: 10,
    rang: UberLevel.UBERVEGETABLE,
  },
  {
    id: 'id3',
    username: 'MIDDLE',
    lastName: 'Shnurov',
    firstName: 'Misha',
    rating: 1000,
    rang: UberLevel.GRASSFEEDING,
  },
  {
    id: 'id4',
    username: 'JUNIOR',
    lastName: 'Drysh',
    firstName: 'Lesha',
    rating: 999,
    rang: UberLevel.VEGETABLE,
  },
  {
    id: 'id5',
    username: 'SENIOR',
    lastName: 'Sobol',
    firstName: 'Ilya',
    rating: 1300,
    rang: UberLevel.FLASHEATING,
  },
  {
    id: 'id6',
    username: 'ALL-WINNER-1',
    lastName: 'Petrov',
    firstName: 'Vasya',
    rating: 2234,
    rang: UberLevel.UBERPREDATOR,
  },
  {
    id: 'id7',
    username: 'ALL-LOSER-1',
    lastName: 'Lol',
    firstName: 'Roma',
    rating: 10,
    rang: UberLevel.UBERVEGETABLE,
  },
  {
    id: 'id8',
    username: 'MIDDLE-1',
    lastName: 'Shnurov',
    firstName: 'Misha',
    rating: 1000,
    rang: UberLevel.GRASSFEEDING,
  },
  {
    id: 'id9',
    username: 'JUNIOR-1',
    lastName: 'Drysh',
    firstName: 'Lesha',
    rating: 999,
    rang: UberLevel.VEGETABLE,
  },
  {
    id: 'id10',
    username: 'SENIOR-1',
    lastName: 'Sobol',
    firstName: 'Ilya',
    rating: 1300,
    rang: UberLevel.FLASHEATING,
  },
]
